// builder/initializer.rs

//! This file is responsible for generating the main `generated_initializer.rs`
//! file, which registers all commands with the flowlang runtime.

use std::collections::{HashMap, HashSet};
use std::path::Path;

use ndata::dataobject::DataObject;

use super::cargo::{find_section_insertion_line, update_cargo_section_lines};
use super::util::{get_project_top_level_path, read_lines_from_file, write_lines_to_file};

/// Renders the initializer's source lines. Pure so tests can assert on the
/// emission without touching the filesystem or the working directory.
///
/// The initializer is FFI-agnostic by design: it wires the statically
/// linked crates and ends with one `flowlang::hotswap::start(magic)` call,
/// which discovers FFI-rooted crates from store metadata and loads (and
/// hot-reloads) them at runtime. Nothing about the FFI crate set — names,
/// watcher lists, loader plumbing — is baked in here anymore, so this file
/// only changes when the *static* crate set changes, and a new FFI library
/// needs no host rebuild or restart.
pub(crate) fn render_main_initializer(crates: &HashMap<String, bool>) -> Vec<String> {
    // Sorted for deterministic output — regenerating an unchanged project
    // must produce an identical file.
    let mut static_crates: Vec<String> = crates
        .iter()
        .filter(|(_, &is_ffi)| !is_ffi)
        .map(|(name, _)| name.clone())
        .collect();
    static_crates.sort();

    let mut lines: Vec<String> = vec![
        "// This file is auto-generated by the flowlang build script. Do not edit.".to_string(),
        "use flowlang::datastore::DataStore;".to_string(),
        "use ndata::NDataConfig;".to_string(),
    ];

    if !static_crates.is_empty() {
        lines.push("use flowlang::rustcmd::{RustCmd, Transform};".to_string());
        for crate_name in &static_crates {
            lines.push(format!("use {};", crate_name.replace("-", "_")));
        }
    }

    lines.push("".to_string());
    lines.push("pub fn initialize_all_commands(magic: (&'static str, NDataConfig)) {".to_string());
    lines.push("    let mut globals = DataStore::globals();".to_string());
    lines.push("    if !globals.has(\"RUST_COMMANDS\") {".to_string());
    lines.push("        globals.put_object(\"RUST_COMMANDS\", ndata::dataobject::DataObject::new());".to_string());
    lines.push("    }".to_string());

    if !static_crates.is_empty() {
        lines.push("    let mut cmd_map = globals.get_object(\"RUST_COMMANDS\");".to_string());

        for crate_name in &static_crates {
            let safe_crate_name = crate_name.replace("-", "_");
            lines.push(format!("\n    // Initialize crate: {}", crate_name));
            lines.push("    {".to_string());
            lines.push("        let mut cmds = Vec::<(String, Transform, String)>::new();".to_string());
            lines.push(format!("        {}::cmdinit(&mut cmds);", safe_crate_name));
            lines.push("        for q in cmds {".to_string());
            lines.push("            let cmd_details = RustCmd::detail(q.0.to_owned(), q.1, q.2.to_owned());".to_string());
            lines.push("            cmd_map.put_object(&q.0, cmd_details);".to_string());
            lines.push("        }".to_string());
            lines.push("    }".to_string());
        }
    }

    lines.push("".to_string());
    lines.push("    // FFI-rooted crates are not named here: flowlang::hotswap discovers".to_string());
    lines.push("    // them from store metadata and loads/reloads them at runtime.".to_string());
    lines.push("    flowlang::hotswap::start(magic);".to_string());
    lines.push("}".to_string());

    lines
}

/// Generates the `src/generated_initializer.rs` file for the main binary.
pub(crate) fn generate_main_initializer(crates: &HashMap<String, bool>) {
    let top_level_path = get_project_top_level_path();
    let generated_file_path = top_level_path.join("src").join("generated_initializer.rs");

    let main_init_lines = render_main_initializer(crates);

    write_lines_to_file(&generated_file_path, &main_init_lines)
        .expect("Failed to write generated initializer file.");

    let main_cargo_path = top_level_path.join("Cargo.toml");
    update_main_cargo_dependencies(&main_cargo_path, crates);
    update_main_cargo_workspace_exclude(&main_cargo_path, crates);
}

/// Adds path dependencies for all sub-crates to the main project's Cargo.toml.
fn update_main_cargo_dependencies(main_cargo_path: &Path, crates: &HashMap<String, bool>) {
    if !main_cargo_path.exists() {
        return;
    }

    let mut lines = read_lines_from_file(&main_cargo_path.to_path_buf()).expect("Failed to read main Cargo.toml");
    let mut dependencies_map = HashMap::new();
    let dep_insertion_line = find_section_insertion_line(&lines, "[dependencies]", &mut dependencies_map);

    let mut new_deps_config = DataObject::new();
    for (crate_name, &is_ffi) in crates.iter() {
        if !is_ffi {
            if !dependencies_map.contains_key(crate_name) {
                let dependency_value = format!("{{ path = \"./{}\" }}", crate_name);
                new_deps_config.put_string(crate_name, &dependency_value);
            }
        }
    }

    if new_deps_config.clone().keys().len() > 0 {
         let (modified, _) = update_cargo_section_lines(
            &mut lines,
            &new_deps_config,
            &mut dependencies_map,
            dep_insertion_line,
            "Dependency",
            "main project's Cargo.toml",
        );

        if modified {
            write_lines_to_file(&main_cargo_path.to_path_buf(), &lines)
                .expect("Failed to write updated main Cargo.toml");
        }
    }
}

/// Adds FFI crates to the workspace.exclude list in the main Cargo.toml.
/// This prevents Cargo from trying to build them as part of the main workspace.
fn update_main_cargo_workspace_exclude(main_cargo_path: &Path, crates: &HashMap<String, bool>) {
    if !main_cargo_path.exists() {
        return;
    }

    let ffi_crates_to_exclude: Vec<_> = crates.iter()
        .filter(|(_, &is_ffi)| is_ffi)
        .map(|(name, _)| name.clone())
        .collect();

    if ffi_crates_to_exclude.is_empty() {
        return; // Nothing to do if there are no FFI crates.
    }

    let mut lines = read_lines_from_file(&main_cargo_path.to_path_buf())
        .expect("Failed to read main Cargo.toml");
    let mut modified = false;

    let workspace_section_index = lines.iter().position(|l| l.trim() == "[workspace]");

    // Find the `exclude =` line, but only within the [workspace] section.
    let mut exclude_line_index: Option<usize> = None;
    if let Some(start_index) = workspace_section_index {
        for i in (start_index + 1)..lines.len() {
            let line = lines[i].trim();
            if line.starts_with('[') { break; } // We've hit the next section.
            if line.starts_with("exclude =") {
                exclude_line_index = Some(i);
                break;
            }
        }
    }

    if let Some(index) = exclude_line_index {
        // --- Case 1: `exclude =` line already exists, so we modify it. ---
        let line = &lines[index];
        let mut existing_crates: HashSet<String> = if let (Some(start), Some(end)) = (line.find('['), line.rfind(']')) {
            line[start + 1..end]
                .split(',')
                .map(|s| s.trim().trim_matches('"').to_string())
                .filter(|s| !s.is_empty())
                .collect()
        } else {
            HashSet::new()
        };

        let initial_count = existing_crates.len();
        for crate_name in ffi_crates_to_exclude {
            existing_crates.insert(crate_name);
        }

        if existing_crates.len() > initial_count {
            let mut sorted_crates: Vec<_> = existing_crates.into_iter().collect();
            sorted_crates.sort();
            let quoted_crates: Vec<_> = sorted_crates.iter().map(|s| format!("\"{}\"", s)).collect();
            let indent = lines[index].find("exclude").unwrap_or(0);
            lines[index] = format!("{}exclude = [{}]", " ".repeat(indent), quoted_crates.join(", "));
            modified = true;
        }

    } else {
        // --- Case 2: No `exclude =` line, so we add it. ---
        let quoted_crates: Vec<_> = ffi_crates_to_exclude.iter().map(|s| format!("\"{}\"", s)).collect();
        let exclude_line = format!("exclude = [{}]", quoted_crates.join(", "));

        if let Some(start_index) = workspace_section_index {
            // [workspace] section exists, just insert the exclude line.
            lines.insert(start_index + 1, exclude_line);
        } else {
            // No [workspace] section, add the whole thing to the end of the file.
            if !lines.last().map_or(false, |l| l.is_empty()) {
                lines.push("".to_string());
            }
            lines.push("[workspace]".to_string());
            lines.push(exclude_line);
        }
        modified = true;
    }

    if modified {
        write_lines_to_file(&main_cargo_path.to_path_buf(), &lines)
            .expect("Failed to write updated main Cargo.toml with workspace excludes");
    }
}

#[cfg(test)]
mod tests {
    use super::render_main_initializer;
    use std::collections::HashMap;

    fn crates(pairs: &[(&str, bool)]) -> HashMap<String, bool> {
        pairs.iter().map(|(n, f)| (n.to_string(), *f)).collect()
    }

    #[test]
    fn initializer_is_ffi_agnostic() {
        let c = crates(&[
            ("newbound_core", false),
            ("cmd", false),
            ("agent", true),
            ("kb", true),
        ]);
        let out = render_main_initializer(&c).join("\n");

        // Static crates are wired exactly as before.
        assert!(out.contains("use newbound_core;"));
        assert!(out.contains("newbound_core::cmdinit(&mut cmds);"));
        assert!(out.contains("cmd::cmdinit(&mut cmds);"));

        // The FFI crates leave no trace: no loader plumbing, no watcher,
        // no crate names — hotswap discovers them from the store.
        assert!(out.contains("flowlang::hotswap::start(magic);"));
        assert!(!out.contains("libloading"));
        assert!(!out.contains("notify"));
        assert!(!out.contains("agent"));
        assert!(!out.contains("kb"));
        assert!(!out.contains("FlowLangLibrary"));
        assert!(!out.contains("LIBRARYHEAP"));
    }

    #[test]
    fn empty_project_still_starts_hotswap() {
        let out = render_main_initializer(&HashMap::new()).join("\n");
        assert!(out.contains("flowlang::hotswap::start(magic);"));
        assert!(out.contains("RUST_COMMANDS"));
        // No static crates: no per-crate imports or registration loop.
        assert!(!out.contains("use flowlang::rustcmd::"));
        assert!(!out.contains("cmd_map"));
    }

    #[test]
    fn emission_is_deterministic_and_normalizes_hyphens() {
        let c = crates(&[("my-tools", false), ("zeta", false), ("alpha", false)]);
        let a = render_main_initializer(&c);
        let b = render_main_initializer(&c);
        assert_eq!(a, b, "same input must render byte-identical output");

        let out = a.join("\n");
        assert!(out.contains("use my_tools;"));
        assert!(out.contains("my_tools::cmdinit(&mut cmds);"));
        // Sorted: alpha's block precedes zeta's.
        let alpha = out.find("// Initialize crate: alpha").unwrap();
        let zeta = out.find("// Initialize crate: zeta").unwrap();
        assert!(alpha < zeta);
    }
}
