//! This file is responsible for generating the main `generated_initializer.rs`
//! file, which registers all commands with the flowlang runtime.

use std::collections::HashMap;
use std::path::Path;

use ndata::dataobject::DataObject;

use super::cargo::{find_section_insertion_line, update_cargo_section_lines};
use super::util::{get_project_top_level_path, read_lines_from_file, write_lines_to_file};

/// Generates the `src/generated_initializer.rs` file for the main binary.
pub(crate) fn generate_main_initializer(crates: &HashMap<String, bool>) {
    let top_level_path = get_project_top_level_path();
    let generated_file_path = top_level_path.join("src").join("generated_initializer.rs");

    // If there are no sub-crates to build, generate a simple empty function.
    if crates.is_empty() {
        let content = vec![
            "// This file is auto-generated by the flowlang build script. Do not edit.".to_string(),
            "// No sub-crates were found to build.".to_string(),
            "pub fn initialize_all_commands() {}".to_string(),
        ];
        write_lines_to_file(&generated_file_path, &content)
            .expect("Failed to write empty generated initializer file.");
        return;
    }

    let mut main_init_lines: Vec<String> = vec![
        "// This file is auto-generated by the flowlang build script. Do not edit.".to_string(),
        "use flowlang::rustcmd::{RustCmd, Transform};".to_string(),
        "use flowlang::datastore::DataStore;".to_string(),
    ];

    let has_ffi_crates = crates.values().any(|&is_ffi| is_ffi);

    if has_ffi_crates {
        main_init_lines.push("\n// FFI Linker module definition".to_string());
        main_init_lines.push("#[repr(C)]".to_string());
        main_init_lines.push("#[derive(Debug)]".to_string());
        main_init_lines.push("pub struct Initializer {".to_string());
        main_init_lines.push("    pub context_placeholder: usize,".to_string());
        main_init_lines.push("    pub cmds: Vec<(String, Transform, String)>,".to_string());
        main_init_lines.push("}".to_string());
    }

    for (crate_name, &is_ffi) in crates.iter() {
        let safe_crate_name = crate_name.replace("-", "_");
        if is_ffi {
            main_init_lines.push(format!("mod {}_ffi {{", safe_crate_name));
            main_init_lines.push("    use super::Initializer;".to_string());
            main_init_lines.push(format!("    #[link(name = \"{}\", kind = \"dylib\")]", crate_name));
            main_init_lines.push("    extern \"C\" {".to_string());
            main_init_lines.push(format!("        pub unsafe extern \"C\" fn mirror_{}(initializer: *mut Initializer);", safe_crate_name));
            main_init_lines.push("    }".to_string());
            main_init_lines.push("}".to_string());
        } else {
            main_init_lines.push(format!("use {};", safe_crate_name));
        }
    }

    // FIX: Generate the function with zero arguments to match the call in `newbound`.
    main_init_lines.push("\npub fn initialize_all_commands() {".to_string());
    main_init_lines.push("    let mut globals = DataStore::globals();".to_string());
    main_init_lines.push("    if !globals.has(\"RUST_COMMANDS\") {".to_string());
    main_init_lines.push("        globals.put_object(\"RUST_COMMANDS\", ndata::dataobject::DataObject::new());".to_string());
    main_init_lines.push("    }".to_string());
    main_init_lines.push("    let mut cmd_map = globals.get_object(\"RUST_COMMANDS\");".to_string());


    for (crate_name, &is_ffi) in crates.iter() {
        let safe_crate_name = crate_name.replace("-", "_");
        main_init_lines.push(format!("\n    // Initialize crate: {}", crate_name));
        main_init_lines.push("    {".to_string());
        main_init_lines.push("        let mut cmds = Vec::new();".to_string());

        if is_ffi {
            main_init_lines.push("        let mut initializer = Initializer {".to_string());
            main_init_lines.push("            context_placeholder: 0, // Placeholder, see REFACTOR_PLAN.md".to_string());
            main_init_lines.push("            cmds: Vec::new(),".to_string());
            main_init_lines.push("        };".to_string());
            main_init_lines.push("        unsafe {".to_string());
            main_init_lines.push(format!("            {}_ffi::mirror_{}(&mut initializer as *mut _);", safe_crate_name, safe_crate_name));
            main_init_lines.push("        }".to_string());
            main_init_lines.push("        cmds.extend(initializer.cmds);".to_string());
        } else {
            main_init_lines.push(format!("        {}::cmdinit(&mut cmds);", safe_crate_name));
        }

        main_init_lines.push("        for q in cmds {".to_string());
        main_init_lines.push("            let cmd_details = RustCmd::detail(q.0.to_owned(), q.1, q.2.to_owned());".to_string());
        main_init_lines.push("            cmd_map.put_object(&q.0, cmd_details);".to_string());
        main_init_lines.push("        }".to_string());
        main_init_lines.push("    }".to_string());
    }

    main_init_lines.push("}".to_string());

    write_lines_to_file(&generated_file_path, &main_init_lines)
        .expect("Failed to write generated initializer file.");

    update_main_cargo_dependencies(&top_level_path.join("Cargo.toml"), crates);
}


/// Adds path dependencies for all sub-crates to the main project's Cargo.toml.
fn update_main_cargo_dependencies(main_cargo_path: &Path, crates: &HashMap<String, bool>) {
    if !main_cargo_path.exists() {
        return;
    }

    let mut lines = read_lines_from_file(&main_cargo_path.to_path_buf()).expect("Failed to read main Cargo.toml");
    let mut dependencies_map = HashMap::new();
    let dep_insertion_line = find_section_insertion_line(&lines, "[dependencies]", &mut dependencies_map);

    let mut new_deps_config = DataObject::new();
    for crate_name in crates.keys() {
        if !dependencies_map.contains_key(crate_name) {
            let dependency_value = format!("{{ path = \"./{}\" }}", crate_name);
            new_deps_config.put_string(crate_name, &dependency_value);
        }
    }

    if new_deps_config.clone().keys().len() > 0 {
         let (modified, _) = update_cargo_section_lines(
            &mut lines,
            &new_deps_config,
            &mut dependencies_map,
            dep_insertion_line,
            "Dependency",
            "main project's Cargo.toml",
        );

        if modified {
            write_lines_to_file(&main_cargo_path.to_path_buf(), &lines)
                .expect("Failed to write updated main Cargo.toml");
        }
    }
}
