// This file is auto-generated by the flowlang build script. Do not edit.
use flowlang::datastore::DataStore;
use ndata::NDataConfig;

pub fn initialize_all_commands(magic: (&'static str, NDataConfig)) {
    let mut globals = DataStore::globals();
    if !globals.has("RUST_COMMANDS") {
        globals.put_object("RUST_COMMANDS", ndata::dataobject::DataObject::new());
    }

    // FFI-rooted crates are not named here: flowlang::hotswap discovers
    // them from store metadata and loads/reloads them at runtime.
    flowlang::hotswap::start(magic);
}
